/**
 * Windows Native Wrapper for Windows.UI.Colors
 *
 * Copyright (c) 2015 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License.
 * Please see the LICENSE included with this distribution for details.
 */

#ifndef _WINDOWS_UI_COLORS_HPP_
#define _WINDOWS_UI_COLORS_HPP_

#include "TitaniumWindows_Native_EXPORT.h"
#include "Titanium/detail/TiBase.hpp"
#include "TitaniumWindows/Utility.hpp"
#include "Platform.Object.hpp"

namespace Titanium
{
	namespace Windows
	{
		namespace UI
		{


		using namespace HAL;

		class TITANIUMWINDOWS_NATIVE_EXPORT Colors : public ::Titanium::Platform::Object, public JSExport<Colors>
		{

		public:
			TITANIUM_PROPERTY_READONLY_DEF(AliceBlue);
			TITANIUM_PROPERTY_READONLY_DEF(AntiqueWhite);
			TITANIUM_PROPERTY_READONLY_DEF(Aqua);
			TITANIUM_PROPERTY_READONLY_DEF(Aquamarine);
			TITANIUM_PROPERTY_READONLY_DEF(Azure);
			TITANIUM_PROPERTY_READONLY_DEF(Beige);
			TITANIUM_PROPERTY_READONLY_DEF(Bisque);
			TITANIUM_PROPERTY_READONLY_DEF(Black);
			TITANIUM_PROPERTY_READONLY_DEF(BlanchedAlmond);
			TITANIUM_PROPERTY_READONLY_DEF(Blue);
			TITANIUM_PROPERTY_READONLY_DEF(BlueViolet);
			TITANIUM_PROPERTY_READONLY_DEF(Brown);
			TITANIUM_PROPERTY_READONLY_DEF(BurlyWood);
			TITANIUM_PROPERTY_READONLY_DEF(CadetBlue);
			TITANIUM_PROPERTY_READONLY_DEF(Chartreuse);
			TITANIUM_PROPERTY_READONLY_DEF(Chocolate);
			TITANIUM_PROPERTY_READONLY_DEF(Coral);
			TITANIUM_PROPERTY_READONLY_DEF(CornflowerBlue);
			TITANIUM_PROPERTY_READONLY_DEF(Cornsilk);
			TITANIUM_PROPERTY_READONLY_DEF(Crimson);
			TITANIUM_PROPERTY_READONLY_DEF(Cyan);
			TITANIUM_PROPERTY_READONLY_DEF(DarkBlue);
			TITANIUM_PROPERTY_READONLY_DEF(DarkCyan);
			TITANIUM_PROPERTY_READONLY_DEF(DarkGoldenrod);
			TITANIUM_PROPERTY_READONLY_DEF(DarkGray);
			TITANIUM_PROPERTY_READONLY_DEF(DarkGreen);
			TITANIUM_PROPERTY_READONLY_DEF(DarkKhaki);
			TITANIUM_PROPERTY_READONLY_DEF(DarkMagenta);
			TITANIUM_PROPERTY_READONLY_DEF(DarkOliveGreen);
			TITANIUM_PROPERTY_READONLY_DEF(DarkOrange);
			TITANIUM_PROPERTY_READONLY_DEF(DarkOrchid);
			TITANIUM_PROPERTY_READONLY_DEF(DarkRed);
			TITANIUM_PROPERTY_READONLY_DEF(DarkSalmon);
			TITANIUM_PROPERTY_READONLY_DEF(DarkSeaGreen);
			TITANIUM_PROPERTY_READONLY_DEF(DarkSlateBlue);
			TITANIUM_PROPERTY_READONLY_DEF(DarkSlateGray);
			TITANIUM_PROPERTY_READONLY_DEF(DarkTurquoise);
			TITANIUM_PROPERTY_READONLY_DEF(DarkViolet);
			TITANIUM_PROPERTY_READONLY_DEF(DeepPink);
			TITANIUM_PROPERTY_READONLY_DEF(DeepSkyBlue);
			TITANIUM_PROPERTY_READONLY_DEF(DimGray);
			TITANIUM_PROPERTY_READONLY_DEF(DodgerBlue);
			TITANIUM_PROPERTY_READONLY_DEF(Firebrick);
			TITANIUM_PROPERTY_READONLY_DEF(FloralWhite);
			TITANIUM_PROPERTY_READONLY_DEF(ForestGreen);
			TITANIUM_PROPERTY_READONLY_DEF(Fuchsia);
			TITANIUM_PROPERTY_READONLY_DEF(Gainsboro);
			TITANIUM_PROPERTY_READONLY_DEF(GhostWhite);
			TITANIUM_PROPERTY_READONLY_DEF(Gold);
			TITANIUM_PROPERTY_READONLY_DEF(Goldenrod);
			TITANIUM_PROPERTY_READONLY_DEF(Gray);
			TITANIUM_PROPERTY_READONLY_DEF(Green);
			TITANIUM_PROPERTY_READONLY_DEF(GreenYellow);
			TITANIUM_PROPERTY_READONLY_DEF(Honeydew);
			TITANIUM_PROPERTY_READONLY_DEF(HotPink);
			TITANIUM_PROPERTY_READONLY_DEF(IndianRed);
			TITANIUM_PROPERTY_READONLY_DEF(Indigo);
			TITANIUM_PROPERTY_READONLY_DEF(Ivory);
			TITANIUM_PROPERTY_READONLY_DEF(Khaki);
			TITANIUM_PROPERTY_READONLY_DEF(Lavender);
			TITANIUM_PROPERTY_READONLY_DEF(LavenderBlush);
			TITANIUM_PROPERTY_READONLY_DEF(LawnGreen);
			TITANIUM_PROPERTY_READONLY_DEF(LemonChiffon);
			TITANIUM_PROPERTY_READONLY_DEF(LightBlue);
			TITANIUM_PROPERTY_READONLY_DEF(LightCoral);
			TITANIUM_PROPERTY_READONLY_DEF(LightCyan);
			TITANIUM_PROPERTY_READONLY_DEF(LightGoldenrodYellow);
			TITANIUM_PROPERTY_READONLY_DEF(LightGray);
			TITANIUM_PROPERTY_READONLY_DEF(LightGreen);
			TITANIUM_PROPERTY_READONLY_DEF(LightPink);
			TITANIUM_PROPERTY_READONLY_DEF(LightSalmon);
			TITANIUM_PROPERTY_READONLY_DEF(LightSeaGreen);
			TITANIUM_PROPERTY_READONLY_DEF(LightSkyBlue);
			TITANIUM_PROPERTY_READONLY_DEF(LightSlateGray);
			TITANIUM_PROPERTY_READONLY_DEF(LightSteelBlue);
			TITANIUM_PROPERTY_READONLY_DEF(LightYellow);
			TITANIUM_PROPERTY_READONLY_DEF(Lime);
			TITANIUM_PROPERTY_READONLY_DEF(LimeGreen);
			TITANIUM_PROPERTY_READONLY_DEF(Linen);
			TITANIUM_PROPERTY_READONLY_DEF(Magenta);
			TITANIUM_PROPERTY_READONLY_DEF(Maroon);
			TITANIUM_PROPERTY_READONLY_DEF(MediumAquamarine);
			TITANIUM_PROPERTY_READONLY_DEF(MediumBlue);
			TITANIUM_PROPERTY_READONLY_DEF(MediumOrchid);
			TITANIUM_PROPERTY_READONLY_DEF(MediumPurple);
			TITANIUM_PROPERTY_READONLY_DEF(MediumSeaGreen);
			TITANIUM_PROPERTY_READONLY_DEF(MediumSlateBlue);
			TITANIUM_PROPERTY_READONLY_DEF(MediumSpringGreen);
			TITANIUM_PROPERTY_READONLY_DEF(MediumTurquoise);
			TITANIUM_PROPERTY_READONLY_DEF(MediumVioletRed);
			TITANIUM_PROPERTY_READONLY_DEF(MidnightBlue);
			TITANIUM_PROPERTY_READONLY_DEF(MintCream);
			TITANIUM_PROPERTY_READONLY_DEF(MistyRose);
			TITANIUM_PROPERTY_READONLY_DEF(Moccasin);
			TITANIUM_PROPERTY_READONLY_DEF(NavajoWhite);
			TITANIUM_PROPERTY_READONLY_DEF(Navy);
			TITANIUM_PROPERTY_READONLY_DEF(OldLace);
			TITANIUM_PROPERTY_READONLY_DEF(Olive);
			TITANIUM_PROPERTY_READONLY_DEF(OliveDrab);
			TITANIUM_PROPERTY_READONLY_DEF(Orange);
			TITANIUM_PROPERTY_READONLY_DEF(OrangeRed);
			TITANIUM_PROPERTY_READONLY_DEF(Orchid);
			TITANIUM_PROPERTY_READONLY_DEF(PaleGoldenrod);
			TITANIUM_PROPERTY_READONLY_DEF(PaleGreen);
			TITANIUM_PROPERTY_READONLY_DEF(PaleTurquoise);
			TITANIUM_PROPERTY_READONLY_DEF(PaleVioletRed);
			TITANIUM_PROPERTY_READONLY_DEF(PapayaWhip);
			TITANIUM_PROPERTY_READONLY_DEF(PeachPuff);
			TITANIUM_PROPERTY_READONLY_DEF(Peru);
			TITANIUM_PROPERTY_READONLY_DEF(Pink);
			TITANIUM_PROPERTY_READONLY_DEF(Plum);
			TITANIUM_PROPERTY_READONLY_DEF(PowderBlue);
			TITANIUM_PROPERTY_READONLY_DEF(Purple);
			TITANIUM_PROPERTY_READONLY_DEF(Red);
			TITANIUM_PROPERTY_READONLY_DEF(RosyBrown);
			TITANIUM_PROPERTY_READONLY_DEF(RoyalBlue);
			TITANIUM_PROPERTY_READONLY_DEF(SaddleBrown);
			TITANIUM_PROPERTY_READONLY_DEF(Salmon);
			TITANIUM_PROPERTY_READONLY_DEF(SandyBrown);
			TITANIUM_PROPERTY_READONLY_DEF(SeaGreen);
			TITANIUM_PROPERTY_READONLY_DEF(SeaShell);
			TITANIUM_PROPERTY_READONLY_DEF(Sienna);
			TITANIUM_PROPERTY_READONLY_DEF(Silver);
			TITANIUM_PROPERTY_READONLY_DEF(SkyBlue);
			TITANIUM_PROPERTY_READONLY_DEF(SlateBlue);
			TITANIUM_PROPERTY_READONLY_DEF(SlateGray);
			TITANIUM_PROPERTY_READONLY_DEF(Snow);
			TITANIUM_PROPERTY_READONLY_DEF(SpringGreen);
			TITANIUM_PROPERTY_READONLY_DEF(SteelBlue);
			TITANIUM_PROPERTY_READONLY_DEF(Tan);
			TITANIUM_PROPERTY_READONLY_DEF(Teal);
			TITANIUM_PROPERTY_READONLY_DEF(Thistle);
			TITANIUM_PROPERTY_READONLY_DEF(Tomato);
			TITANIUM_PROPERTY_READONLY_DEF(Transparent);
			TITANIUM_PROPERTY_READONLY_DEF(Turquoise);
			TITANIUM_PROPERTY_READONLY_DEF(Violet);
			TITANIUM_PROPERTY_READONLY_DEF(Wheat);
			TITANIUM_PROPERTY_READONLY_DEF(White);
			TITANIUM_PROPERTY_READONLY_DEF(WhiteSmoke);
			TITANIUM_PROPERTY_READONLY_DEF(Yellow);
			TITANIUM_PROPERTY_READONLY_DEF(YellowGreen);


			Colors(const JSContext&) TITANIUM_NOEXCEPT;

			virtual ~Colors() = default;
			Colors(const Colors&) = default;
			Colors& operator=(const Colors&) = default;
#ifdef TITANIUM_MOVE_CTOR_AND_ASSIGN_DEFAULT_ENABLE
			Colors(Colors&&)                 = default;
			Colors& operator=(Colors&&)      = default;
#endif

			static void JSExportInitialize();

			virtual void postCallAsConstructor(const JSContext& js_context, const std::vector<JSValue>& arguments) override;

			::Windows::UI::Colors^ unwrapWindows_UI_Colors() const;
			void wrap(::Windows::UI::Colors^ object);

		private:
			::Windows::UI::Colors^ unwrap() const;

		};

		} // namespace UI
	} // namespace Windows
} // namespace Titanium
#endif // _WINDOWS_UI_COLORS_HPP_
